import React, { useState } from 'react';
import { useVitals } from '../context/VitalsContext';
import { Bell, AlertTriangle, CheckCircle2, ShieldAlert, Trash2, Filter } from 'lucide-react';

export const AlertsView: React.FC = () => {
  const { alerts, acknowledgeAlert, clearAlerts } = useVitals();
  const [filterSeverity, setFilterSeverity] = useState<'ALL' | 'CRITICAL' | 'WARNING'>('ALL');

  const filteredAlerts = alerts.filter(a => {
    if (filterSeverity === 'ALL') return true;
    return a.severity === filterSeverity;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="glass-panel rounded-2xl p-5 border border-[#1f2e56] flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-amber-950/80 border border-amber-800 rounded-xl text-amber-400">
            <Bell className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-lg font-black text-white uppercase tracking-wide">
              PHYSIOLOGICAL ALERTS & NOTIFICATIONS
            </h2>
            <p className="text-xs text-slate-400">Audit log of threshold exceptions generated by edge telemetry stream</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Severity Filter */}
          <div className="flex items-center gap-1 bg-[#131e3a] p-1 rounded-xl border border-[#1f2e56]">
            <Filter className="w-3.5 h-3.5 text-slate-400 ml-2" />
            <button
              onClick={() => setFilterSeverity('ALL')}
              className={`px-3 py-1 text-xs font-bold rounded-lg ${
                filterSeverity === 'ALL' ? 'bg-cyan-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              All ({alerts.length})
            </button>
            <button
              onClick={() => setFilterSeverity('CRITICAL')}
              className={`px-3 py-1 text-xs font-bold rounded-lg ${
                filterSeverity === 'CRITICAL' ? 'bg-rose-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Critical
            </button>
            <button
              onClick={() => setFilterSeverity('WARNING')}
              className={`px-3 py-1 text-xs font-bold rounded-lg ${
                filterSeverity === 'WARNING' ? 'bg-amber-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Warning
            </button>
          </div>

          <button
            onClick={clearAlerts}
            className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-bold transition-colors flex items-center gap-1.5"
          >
            <Trash2 className="w-3.5 h-3.5" /> Clear All
          </button>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3">
        {filteredAlerts.length > 0 ? (
          filteredAlerts.map((alert) => (
            <div
              key={alert.id}
              className={`glass-panel rounded-2xl p-4 border transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 ${
                alert.severity === 'CRITICAL'
                  ? 'border-rose-500/80 bg-rose-950/30'
                  : 'border-amber-500/60 bg-amber-950/20'
              } ${alert.acknowledged ? 'opacity-60' : ''}`}
            >
              <div className="flex items-start gap-3">
                {alert.severity === 'CRITICAL' ? (
                  <ShieldAlert className="w-5 h-5 text-rose-400 shrink-0 mt-0.5 animate-bounce" />
                ) : (
                  <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                )}
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-white text-sm">{alert.patientName}</span>
                    <span className="font-mono text-xs px-2 py-0.5 rounded bg-[#131e3a] border border-[#1f2e56] text-cyan-300 font-bold">
                      {alert.patientId}
                    </span>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                      alert.severity === 'CRITICAL' ? 'bg-rose-600 text-white' : 'bg-amber-600 text-white'
                    }`}>
                      {alert.severity}
                    </span>
                  </div>

                  <p className="text-xs text-slate-200">{alert.message}</p>

                  <div className="flex items-center gap-4 text-[10px] text-slate-400 font-mono pt-1">
                    <span>Parameter: <strong className="text-slate-200">{alert.vitalType}</strong></span>
                    <span>Value: <strong className="text-cyan-400">{alert.value}</strong></span>
                    <span>Time: <strong>{alert.timestamp}</strong></span>
                  </div>
                </div>
              </div>

              <div>
                {alert.acknowledged ? (
                  <span className="px-3 py-1.5 rounded-xl bg-emerald-950 text-emerald-400 border border-emerald-800 text-xs font-bold flex items-center gap-1">
                    <CheckCircle2 className="w-3.5 h-3.5" /> Acknowledged
                  </span>
                ) : (
                  <button
                    onClick={() => acknowledgeAlert(alert.id)}
                    className="px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-white rounded-xl text-xs font-bold shadow-md transition-colors"
                  >
                    Acknowledge
                  </button>
                )}
              </div>
            </div>
          ))
        ) : (
          <div className="glass-panel rounded-2xl p-8 text-center text-slate-400 space-y-2 border border-[#1f2e56]">
            <CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto" />
            <h3 className="text-sm font-bold text-slate-200">No Alerts Pending</h3>
            <p className="text-xs">All patient vital parameters are currently within normal baseline thresholds.</p>
          </div>
        )}
      </div>
    </div>
  );
};
